auth:
  type: DISABLED

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.hibernate.validator: WARN
